[features]
seeds = false
skip-lint = false

[programs.localnet]
raydium_amm_v3 = "52bqGxXwned1bmrA624kvzTo1EmFqntfThg6rRqyrGSC" 

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "C:\\Users\\administrator\\.config\\solana\\id.json"

[scripts]
test = "cargo test --test integration -- --nocapture"

[test]
startup_wait = 10000